### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by oparkins** [oparkins/farms#1]
You will need: 

- Ruby
- Gem (it is a module for ruby)
- Node.js (use npm)

**Comment by Tristan2252** [comment]
This might be useful [Setup Ruby On Rails on](https://gorails.com/setup/ubuntu/16.04)

**Comment by Tyler799** [comment]
I think I should be set up on my end. 

- npm 5.6
- nodejs 8.9.4
- ruby 2.5.0p0
- gem 2.73
- rails 5.1.4
- Ubuntu 64-bit 17.10
- VS Code 1.19.3

Though I did get some weirdness. Just doing version number checks it all works out, but we'll see in practice if everything is actually working. I'm assuming there are some plugins for VS Code we might want to look into?

**Comment by oparkins** [comment]
we will fix issues that come along.
