### ISSUE TITLE
Get Browser Back button working

### ISSUE THREAD

**Issue by oparkins** [oparkins/farms#35]

**Comment by oparkins** [comment]
Added support for this in commit fa78203. I will soon start a pull request for it. 

It is a little sketchy how it is done. This is because we are not using a router, but we are just using a simpler method to edit the history of the browser.  All the code is in

**Comment by Tristan2252** [comment]
im getting this error:
```
Error in ./src/components/App.js
Module not found: 'history/createBrowserHistory' in /home/ubuntu/Documents/326/project/farms/client/src/components
```

**Comment by Tristan2252** [comment]
looks like running `npm install` fixes it
It looks good to me!
